---
- name: update AlmaLinux OS
  hosts: localhost
  become: true
  tasks:
    - name: update AlmaLinux OS
      ansible.builtin.package:
        name: "*"
        state: latest
    - name: reboot the server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
